apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.mailerlite.com
spec:
  group: mailerlite.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiToken:
                  type: string
                senderEmail:
                  type: string
          required:
            - apiToken
            - senderEmail
