apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.mailerlite.com
spec:
  group: mailerlite.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                senderConfigRef:
                  type: string
                recipientEmail:
                  type: string
                subject:
                  type: string
                body:
                  type: string
          required:
            - senderConfigRef
            - recipientEmail
            - subject
            - body
            - messageId
  subresources:
    status: {}
